name: ats-di-test

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: Docker Image Tag
        required: true
        default: '0.0.1'
        type: string
      do_push:
        description: Push
        required: true
        default: true
        type: boolean

env:
  DOCKER_IMAGE_NAME: jotools/ats-codesign

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        arch: [amd64, arm64v8]
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm64v8
            platform: linux/arm64/v8
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd ./dockerimage
          docker build \
              --no-cache \
              --platform ${{ matrix.platform }} \
              --build-arg ARCH=${{ matrix.arch }}
              -t ${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.docker_image_tag }}-${{ matrix.arch }} \
              .

      - name: Push Docker image
        if: "${{ inputs.do_push == true }}"
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.docker_image_tag }}-${{ matrix.platform }}
